# generated by datamodel-codegen:
#   filename:  agent_provenance.schema.json
#   timestamp: 2026-05-26T15:45:01+00:00

from __future__ import annotations

from datetime import date

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class ModelDescriptor(BaseModel):
    """
    One model used in producing the contribution. Only `name` is required; every other field is recommended-but-optional, so captures degrade gracefully when metadata is partial.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., max_length=128, min_length=1)
    """
    Full canonical marketing name (e.g. 'Claude Opus 4.7', 'GPT-5', 'Gemini 3 Pro', 'Llama 4 405B'). Vendor + series + version, fully spelled. This is the human-facing identifier — what appears in citations and search results. RRP-0026 §`Author.name` convention says agent authors SHOULD set Author.name to match models[0].name in the single-model case.
    """
    vendor: str | None = Field(None, pattern="^[a-z][a-z0-9-]{0,31}$")
    """
    Vendor identifier, lowercase shortname (anthropic, openai, google, meta, mistral, deepseek, ...). Used for cohort aggregation on the vendor axis.
    """
    family: str | None = Field(None, pattern="^[a-z][a-z0-9-]{0,31}$")
    """
    Family within a vendor (claude, gpt, gemini, llama, mistral, deepseek). One vendor may have multiple families; one family may have multiple series.
    """
    series: str | None = Field(None, pattern="^[a-z][a-z0-9-]{0,31}$")
    """
    Model series within a family (opus, sonnet, haiku, gpt-5, gpt-4o, o3, gemini-pro, gemini-flash). Distinguishes capability tiers.
    """
    version: str | None = Field(None, max_length=32)
    """
    Marketing version string ('4.7', '5.0', '3.0-pro'). Free-form within the family/series convention; vendors are inconsistent here so the schema doesn't enforce a pattern.
    """
    release_pin: str | None = Field(None, pattern="^[a-z0-9][a-z0-9.-]{0,127}$")
    """
    Exact API model identifier as exposed by the inference vendor (e.g. 'claude-opus-4-7-20260520', 'gpt-5-2026-04-15'). Lowercase, hyphens/dots/digits. The replicator's source of truth: this is what gets passed to the API to reproduce the exact snapshot.
    """
    release_date: date | None = None
    """
    Date the model snapshot was released by the vendor, YYYY-MM-DD. Typically encoded in the release_pin suffix.
    """
    context_window_tokens: int | None = Field(None, ge=0)
    """
    Effective context window the agent was operating in.
    """
    inference_provider: str | None = Field(None, max_length=64)
    """
    Where the inference ran when distinct from `vendor` (e.g. 'openrouter', 'vertex-ai', 'azure-openai', 'aws-bedrock'). Omit if vendor and provider are the same.
    """


class AgentProvenance1(BaseModel):
    """
    Per-write provenance metadata recording which model(s) produced an agent contribution, when, and where (RRP-0025 + RRP-0026). Attaches to Author entries, Annotation.created_by, and SubmissionRequest.created_by. Multi-model: a single contribution can declare multiple models (e.g. Claude Opus 4.7 for prose + GPT-5 for code review) via the `models[]` array. Backward compat with RRP-0025: the flat fields (model_slug, model_family, model_release_date, context_window_tokens) at the root are deprecated aliases — consumers MUST prefer `models[0].*` when both are present.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    models: list[ModelDescriptor] = Field(..., max_length=16, min_length=1)
    """
    Ordered list of models used for this contribution. Primary model first by convention (not enforced). For single-model agents (the common case), the array has one entry. See RRP-0026.
    """
    inference_started_at: AwareDatetime | None = None
    """
    Wall-clock UTC timestamp when the agent began the work.
    """
    inference_ended_at: AwareDatetime | None = None
    """
    Wall-clock UTC timestamp when the agent completed the work.
    """
    inference_wall_seconds: float | None = Field(None, ge=0.0)
    """
    Total wall-clock seconds spent on this contribution.
    """
    inference_environment: str | None = Field(None, max_length=128)
    """
    Human-readable identifier for where the inference ran. Free-form. Examples: 'Claude Code CLI', 'claude.ai web', 'Anthropic API', 'OpenAI Playground', 'OpenRouter + Claude Code CLI' for multi-vendor setups.
    """
    operator_orcid: str | None = Field(None, pattern="^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$")
    """
    ORCID iD of the human operator who initiated this agent run, if known. Distinct from the agent's own identity — captures attribution back to a human-in-the-loop for accountability.
    """
    model_slug: str | None = Field(None, deprecated=True, pattern="^[a-z0-9][a-z0-9-]{0,127}$")
    """
    DEPRECATED (RRP-0026): alias for `models[0].release_pin || models[0].name`. Consumers reading this field MUST prefer `models[0].*` when both are present. Writers SHOULD emit `models[]` and omit this field.
    """
    model_family: str | None = Field(None, deprecated=True, pattern="^[a-z][a-z0-9]{0,31}$")
    """
    DEPRECATED (RRP-0026): alias for `models[0].family`.
    """
    model_release_date: date | None = Field(None, deprecated=True)
    """
    DEPRECATED (RRP-0026): alias for `models[0].release_date`.
    """
    context_window_tokens: int | None = Field(None, deprecated=True, ge=0)
    """
    DEPRECATED (RRP-0026): alias for `models[0].context_window_tokens`.
    """


class AgentProvenance2(BaseModel):
    """
    Per-write provenance metadata recording which model(s) produced an agent contribution, when, and where (RRP-0025 + RRP-0026). Attaches to Author entries, Annotation.created_by, and SubmissionRequest.created_by. Multi-model: a single contribution can declare multiple models (e.g. Claude Opus 4.7 for prose + GPT-5 for code review) via the `models[]` array. Backward compat with RRP-0025: the flat fields (model_slug, model_family, model_release_date, context_window_tokens) at the root are deprecated aliases — consumers MUST prefer `models[0].*` when both are present.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    models: list[ModelDescriptor] | None = Field(None, max_length=16, min_length=1)
    """
    Ordered list of models used for this contribution. Primary model first by convention (not enforced). For single-model agents (the common case), the array has one entry. See RRP-0026.
    """
    inference_started_at: AwareDatetime | None = None
    """
    Wall-clock UTC timestamp when the agent began the work.
    """
    inference_ended_at: AwareDatetime | None = None
    """
    Wall-clock UTC timestamp when the agent completed the work.
    """
    inference_wall_seconds: float | None = Field(None, ge=0.0)
    """
    Total wall-clock seconds spent on this contribution.
    """
    inference_environment: str | None = Field(None, max_length=128)
    """
    Human-readable identifier for where the inference ran. Free-form. Examples: 'Claude Code CLI', 'claude.ai web', 'Anthropic API', 'OpenAI Playground', 'OpenRouter + Claude Code CLI' for multi-vendor setups.
    """
    operator_orcid: str | None = Field(None, pattern="^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$")
    """
    ORCID iD of the human operator who initiated this agent run, if known. Distinct from the agent's own identity — captures attribution back to a human-in-the-loop for accountability.
    """
    model_slug: str = Field(..., deprecated=True, pattern="^[a-z0-9][a-z0-9-]{0,127}$")
    """
    DEPRECATED (RRP-0026): alias for `models[0].release_pin || models[0].name`. Consumers reading this field MUST prefer `models[0].*` when both are present. Writers SHOULD emit `models[]` and omit this field.
    """
    model_family: str | None = Field(None, deprecated=True, pattern="^[a-z][a-z0-9]{0,31}$")
    """
    DEPRECATED (RRP-0026): alias for `models[0].family`.
    """
    model_release_date: date | None = Field(None, deprecated=True)
    """
    DEPRECATED (RRP-0026): alias for `models[0].release_date`.
    """
    context_window_tokens: int | None = Field(None, deprecated=True, ge=0)
    """
    DEPRECATED (RRP-0026): alias for `models[0].context_window_tokens`.
    """


class AgentProvenance(RootModel[AgentProvenance1 | AgentProvenance2]):
    root: AgentProvenance1 | AgentProvenance2 = Field(
        ...,
        examples=[
            {
                "models": [
                    {
                        "name": "Claude Opus 4.7",
                        "vendor": "anthropic",
                        "family": "claude",
                        "series": "opus",
                        "version": "4.7",
                        "release_pin": "claude-opus-4-7-20260520",
                        "release_date": "2026-05-20",
                        "context_window_tokens": 200000,
                    }
                ],
                "inference_started_at": "2026-05-26T14:12:00Z",
                "inference_ended_at": "2026-05-26T14:12:18Z",
                "inference_wall_seconds": 18,
                "inference_environment": "Claude Code CLI",
                "operator_orcid": "0009-0002-0561-6499",
            },
            {
                "models": [
                    {
                        "name": "Claude Opus 4.7",
                        "vendor": "anthropic",
                        "family": "claude",
                        "series": "opus",
                        "version": "4.7",
                        "release_pin": "claude-opus-4-7-20260520",
                        "release_date": "2026-05-20",
                        "context_window_tokens": 200000,
                    },
                    {
                        "name": "GPT-5",
                        "vendor": "openai",
                        "family": "gpt",
                        "series": "gpt-5",
                        "version": "5.0",
                        "release_pin": "gpt-5-2026-04-15",
                        "release_date": "2026-04-15",
                        "context_window_tokens": 1000000,
                        "inference_provider": "openrouter",
                    },
                ],
                "inference_environment": "OpenRouter + Claude Code CLI",
                "operator_orcid": "0009-0002-0561-6499",
            },
        ],
        title="AgentProvenance",
    )
    """
    Per-write provenance metadata recording which model(s) produced an agent contribution, when, and where (RRP-0025 + RRP-0026). Attaches to Author entries, Annotation.created_by, and SubmissionRequest.created_by. Multi-model: a single contribution can declare multiple models (e.g. Claude Opus 4.7 for prose + GPT-5 for code review) via the `models[]` array. Backward compat with RRP-0025: the flat fields (model_slug, model_family, model_release_date, context_window_tokens) at the root are deprecated aliases — consumers MUST prefer `models[0].*` when both are present.
    """
