# generated by datamodel-codegen:
#   filename:  agent_provenance.schema.json
#   timestamp: 2026-05-26T15:01:56+00:00

from __future__ import annotations

from datetime import date

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class AgentProvenance(BaseModel):
    """
    Per-write provenance metadata recording which model produced an agent contribution, when, and where (RRP-0025). Attaches to Author entries, Annotation.created_by, and SubmissionRequest.created_by. Distinct from agent_handle: a stable handle can use multiple model snapshots over time; provenance records the snapshot used for each individual write.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    model_slug: str = Field(..., pattern="^[a-z0-9][a-z0-9-]{0,127}$")
    """
    Raw model identifier as exposed by the inference vendor. Lowercase, hyphens only, no spaces or dots. Examples: `claude-opus-4-7-20260520`, `gpt-5-20260415`, `gemini-3-pro-20260518`.
    """
    model_family: str | None = Field(None, pattern="^[a-z][a-z0-9]{0,31}$")
    """
    Coarser-grained vendor family identifier for cohort aggregation. Examples: `claude`, `gpt`, `gemini`, `llama`, `mistral`, `deepseek`.
    """
    model_release_date: date | None = None
    """
    Date the model snapshot was released by the vendor, YYYY-MM-DD. Typically encoded in the slug suffix; this field is the canonical machine-readable form.
    """
    inference_started_at: AwareDatetime | None = None
    """
    Wall-clock UTC timestamp when the agent began the work producing this contribution. Stamped by the CLI at submit time; not hand-edited at the Author level.
    """
    inference_ended_at: AwareDatetime | None = None
    """
    Wall-clock UTC timestamp when the agent completed the work.
    """
    inference_wall_seconds: float | None = Field(None, ge=0.0)
    """
    Total wall-clock seconds spent on this contribution. Auditable cost signal for downstream cost-aware aggregations.
    """
    inference_environment: str | None = Field(None, max_length=128)
    """
    Human-readable identifier for where the inference ran. Free-form. Examples: `Claude Code CLI`, `claude.ai web`, `Anthropic API`, `OpenAI Playground`.
    """
    context_window_tokens: int | None = Field(None, ge=0)
    """
    Effective context window the agent was operating in. Useful for interpreting what context was available.
    """
    operator_orcid: str | None = Field(None, pattern="^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$")
    """
    ORCID iD of the human operator who initiated this agent run, if known. Captures attribution back to a human-in-the-loop for accountability without conflating it with the agent's own identity.
    """
