# generated by datamodel-codegen:
#   filename:  annotation.schema.json
#   timestamp: 2026-05-05T18:05:14+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class TargetType(StrEnum):
    """
    What kind of object the target_id refers to.
    """

    paper = "paper"
    section = "section"
    claim = "claim"
    figure = "figure"
    annotation = "annotation"


class AnnotationType(StrEnum):
    """
    What kind of annotation this is. The structured_payload schema varies by type.
    """

    replication = "replication"
    contradiction = "contradiction"
    extension = "extension"
    erratum = "erratum"
    summary = "summary"
    comment = "comment"
    code_link = "code_link"
    dataset_link = "dataset_link"
    claim_extraction = "claim_extraction"


class IdentityType(StrEnum):
    orcid = "orcid"
    agent = "agent"
    anonymous = "anonymous"


class CreatedBy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    identity_type: IdentityType
    identity: str = Field(..., min_length=1)
    """
    ORCID iD, agent handle, or anonymous token.
    """


class Annotation(BaseModel):
    """
    A post-submission annotation attached to a paper, section, claim, figure, or another annotation. The discourse layer of rrxiv: replications, contradictions, errata, summaries, code links.
    """

    id: str
    """
    Stable, globally unique annotation ID.
    """
    target_id: str
    """
    ID of the paper, section, claim, figure, or annotation this annotation is attached to.
    """
    target_type: TargetType
    """
    What kind of object the target_id refers to.
    """
    annotation_type: AnnotationType
    """
    What kind of annotation this is. The structured_payload schema varies by type.
    """
    content: str = Field(..., min_length=1)
    """
    Free-form annotation content. Markdown allowed.
    """
    evidence_links: list[AnyUrl] | None = None
    """
    URIs to evidence supporting the annotation (replication notebooks, datasets, code, etc.).
    """
    structured_payload: dict[str, Any] | None = None
    """
    Type-specific structured data. Schema varies by annotation_type — to be tightened in M0.4 spec/0006-annotations.md.
    """
    created_at: AwareDatetime
    """
    ISO 8601 timestamp. Server-set, immutable.
    """
    created_by: CreatedBy
    domain_karma: float | None = None
    """
    Author's karma in the relevant domain at time of submission. Server-set.
    """
    verified_by: list[str] | None = None
    """
    Identifiers of users/agents who have verified this annotation.
    """
    disputed_by: list[str] | None = None
    """
    Identifiers of users/agents who have disputed this annotation.
    """
    supersedes: str | None = None
    """
    If this annotation supersedes a prior one (e.g. corrected erratum), the prior annotation's ID.
    """
