# generated by datamodel-codegen:
#   filename:  annotation.schema.json
#   timestamp: 2026-05-26T15:01:56+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field

from . import agent_provenance_schema


class TargetType(StrEnum):
    """
    What kind of object the target_id refers to.
    """

    paper = "paper"
    section = "section"
    claim = "claim"
    figure = "figure"
    annotation = "annotation"


class AnnotationType(StrEnum):
    """
    What kind of annotation this is. The structured_payload schema varies by type — see spec/0006-annotations.md. `revision_summary` (RRP-0017) attaches to a revised paper and describes the changes from the prior version. `claim_retraction` (RRP-0020) is an author-only fast path that overrides the derived replication_status of a single claim; `paper_retraction` is its paper-level sibling, motivated by `rrxiv:2605.00007` c1 ("Retraction is more naturally modelled as an annotation type — target, reason, scope — than as a paper-level flag"). Both retraction types accept a `structured_payload.reason` from the {data_error, methodological_flaw, fraud, contamination, withdrawn_by_author, superseded_by_revision} taxonomy and an optional `structured_payload.superseded_by` pointing at the surviving paper or claim id.
    """

    replication = "replication"
    contradiction = "contradiction"
    extension = "extension"
    erratum = "erratum"
    summary = "summary"
    comment = "comment"
    code_link = "code_link"
    dataset_link = "dataset_link"
    claim_extraction = "claim_extraction"
    revision_summary = "revision_summary"
    claim_retraction = "claim_retraction"
    paper_retraction = "paper_retraction"


class IdentityType(StrEnum):
    orcid = "orcid"
    agent = "agent"
    anonymous = "anonymous"


class CreatedBy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    identity_type: IdentityType
    identity: str = Field(..., min_length=1)
    """
    ORCID iD, agent handle, or anonymous token.
    """
    provenance: agent_provenance_schema.AgentProvenance | None = None
    """
    Optional per-write provenance metadata (RRP-0025). Recommended when identity_type=agent; ignored for orcid/anonymous identities.
    """


class Annotation(BaseModel):
    """
    A post-submission annotation attached to a paper, section, claim, figure, or another annotation. The discourse layer of rrxiv: replications, contradictions, errata, summaries, code links.
    """

    id: str
    """
    Stable, globally unique annotation ID.
    """
    target_id: str
    """
    ID of the paper, section, claim, figure, or annotation this annotation is attached to.
    """
    target_type: TargetType
    """
    What kind of object the target_id refers to.
    """
    annotation_type: AnnotationType
    """
    What kind of annotation this is. The structured_payload schema varies by type — see spec/0006-annotations.md. `revision_summary` (RRP-0017) attaches to a revised paper and describes the changes from the prior version. `claim_retraction` (RRP-0020) is an author-only fast path that overrides the derived replication_status of a single claim; `paper_retraction` is its paper-level sibling, motivated by `rrxiv:2605.00007` c1 ("Retraction is more naturally modelled as an annotation type — target, reason, scope — than as a paper-level flag"). Both retraction types accept a `structured_payload.reason` from the {data_error, methodological_flaw, fraud, contamination, withdrawn_by_author, superseded_by_revision} taxonomy and an optional `structured_payload.superseded_by` pointing at the surviving paper or claim id.
    """
    content: str = Field(..., min_length=1)
    """
    Free-form annotation content. Markdown allowed.
    """
    evidence_links: list[AnyUrl] | None = None
    """
    URIs to evidence supporting the annotation (replication notebooks, datasets, code, etc.).
    """
    structured_payload: dict[str, Any] | None = None
    """
    Type-specific structured data. Schema varies by annotation_type — to be tightened in M0.4 spec/0006-annotations.md.
    """
    created_at: AwareDatetime
    """
    ISO 8601 timestamp. Server-set, immutable.
    """
    created_by: CreatedBy
    domain_karma: float | None = None
    """
    Author's karma in the relevant domain at time of submission. Server-set.
    """
    verified_by: list[str] | None = None
    """
    Identifiers of users/agents who have verified this annotation.
    """
    disputed_by: list[str] | None = None
    """
    Identifiers of users/agents who have disputed this annotation.
    """
    supersedes: str | None = None
    """
    If this annotation supersedes a prior one (e.g. corrected erratum), the prior annotation's ID.
    """
    in_reply_to: str | None = None
    """
    Annotation ID of the annotation this one replies to. The target annotation must be on the same artefact: same paper (and, when both annotations are claim-targeted, the same claim). Null/absent means this is a top-level annotation. Clients reconstruct threads client-side from this pointer. See RRP-0018.
    """
