# generated by datamodel-codegen:
#   filename:  cir.schema.json
#   timestamp: 2026-05-30T22:01:20+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field

from . import (
    annotation_schema,
    citation_schema,
    claim_schema,
    figure_schema,
    paper_schema,
    section_schema,
)


class CanonicalIntermediateRepresentationCir(BaseModel):
    """
    The full structured representation of a rrxiv paper. A Paper's metadata plus its derived structure (sections, claims, citations, figures, annotations). Extracted from TeX/Typst source by the rrxiv parser. The unit of agent-readable knowledge in the rrxiv corpus.
    """

    rrxiv_version: str = Field(..., examples=["0.1.0"], pattern="^[0-9]+\\.[0-9]+\\.[0-9]+$")
    """
    Version of the rrxiv protocol this CIR conforms to. SemVer.
    """
    id: str = Field(..., examples=["01923f8e-5b2a-7c4d-9e1f-3a2b1c0d4e5f"])
    """
    Stable, canonical machine identifier for this paper. Server-assigned UUIDv7 (RFC 9562) — opaque to clients; do NOT parse, derive, or construct it. Once assigned, NEVER changes. Humans cite the `id_slug`, not this. See RRP-0029.
    """
    id_slug: str | None = Field(
        None,
        examples=["rrxiv:2402.00128", "rrxiv:2605.00001"],
        pattern="^rrxiv:[0-9]{4}\\.[0-9]{5}$",
    )
    """
    Human-friendly paper identifier of the form rrxiv:YYMM.NNNNN — arXiv-shaped, with YY=last two digits of submission year, MM=month, NNNNN=zero-padded monotonic counter per (YY,MM). Server-minted at submission, unique per server instance. Used in URLs, citations, and human-readable references. The canonical machine identifier remains `id`. Once assigned, NEVER changes. Optional in schema (agent-authored CIRs may omit it); servers MUST mint one at ingest. See RRP-0013.
    """
    version: str = Field(..., examples=["v1", "v2"], pattern="^v[0-9]+$")
    """
    Paper revision. The same paper may have v1, v2, etc. Each version is immutable once submitted.
    """
    previous_version: str | None = None
    """
    The previous version's `id` (server-assigned UUIDv7), if any. Null for v1.
    """
    title: str = Field(..., max_length=500, min_length=1)
    authors: list[paper_schema.Author] = Field(..., min_length=1)
    abstract: str
    """
    Plain-text abstract. Math should be expressed in LaTeX inline.
    """
    submitted_at: AwareDatetime
    """
    ISO 8601 timestamp when this version was submitted to rrxiv. Set by server, immutable.
    """
    license: str = Field(..., examples=["CC-BY-4.0", "CC-BY-SA-4.0", "CC0-1.0"])
    """
    SPDX license identifier for the paper content. rrxiv recommends CC-BY-4.0.
    """
    topics: list[str] | None = None
    """
    Topic IDs from the rrxiv controlled vocabulary. May be added or refined post-submission via annotations.
    """
    source: paper_schema.Source
    sections: list[section_schema.Section] | None = None
    claims: list[claim_schema.Claim] | None = None
    """
    Claims extracted from this paper. May be added post-hoc by annotators or agents, subject to author confirmation for canonical status.
    """
    citations: list[citation_schema.Citation] | None = None
    figures: list[figure_schema.Figure] | None = None
    annotations: list[annotation_schema.Annotation] | None = None
    """
    Post-submission annotations attached to this paper. Populated lazily; servers may return [] and require a separate query for annotations.
    """
