# generated by datamodel-codegen:
#   filename:  citation.schema.json
#   timestamp: 2026-05-26T15:01:56+00:00

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, Field, RootModel


class Citation1(BaseModel):
    """
    A citation from a rrxiv paper to another work. May reference another rrxiv paper (target_paper_id), an external work via DOI/arXiv/URL, or a raw BibTeX entry.
    """

    id: str
    """
    Stable, globally unique citation ID within a paper.
    """
    key: str = Field(..., min_length=1)
    """
    BibTeX key as it appears in the paper source.
    """
    target_paper_id: str
    """
    If the cited work is itself in rrxiv, its paper ID. Null otherwise.
    """
    target_doi: str | None = Field(None, pattern="^10\\.[0-9]{4,9}/[-._;()/:a-zA-Z0-9]+$")
    """
    DOI of the cited work, if any. DOIs are case-insensitive in matching; the registrant's chosen case is preserved.
    """
    target_arxiv_id: str | None = None
    """
    arXiv identifier of the cited work, if any (e.g. '2305.12345').
    """
    target_url: AnyUrl | None = None
    """
    Generic URL fallback for the cited work.
    """
    bibtex_entry: str | None = None
    """
    Full BibTeX entry for the cited work. Always present so the citation is verifiable even if external links rot.
    """
    referenced_in: list[str] | None = None
    """
    IDs of sections or claims that cite this work.
    """
    is_self_citation: bool | None = False
    """
    True if the cited work shares an author with the citing paper.
    """


class Citation2(BaseModel):
    """
    A citation from a rrxiv paper to another work. May reference another rrxiv paper (target_paper_id), an external work via DOI/arXiv/URL, or a raw BibTeX entry.
    """

    id: str
    """
    Stable, globally unique citation ID within a paper.
    """
    key: str = Field(..., min_length=1)
    """
    BibTeX key as it appears in the paper source.
    """
    target_paper_id: str | None = None
    """
    If the cited work is itself in rrxiv, its paper ID. Null otherwise.
    """
    target_doi: str = Field(..., pattern="^10\\.[0-9]{4,9}/[-._;()/:a-zA-Z0-9]+$")
    """
    DOI of the cited work, if any. DOIs are case-insensitive in matching; the registrant's chosen case is preserved.
    """
    target_arxiv_id: str | None = None
    """
    arXiv identifier of the cited work, if any (e.g. '2305.12345').
    """
    target_url: AnyUrl | None = None
    """
    Generic URL fallback for the cited work.
    """
    bibtex_entry: str | None = None
    """
    Full BibTeX entry for the cited work. Always present so the citation is verifiable even if external links rot.
    """
    referenced_in: list[str] | None = None
    """
    IDs of sections or claims that cite this work.
    """
    is_self_citation: bool | None = False
    """
    True if the cited work shares an author with the citing paper.
    """


class Citation3(BaseModel):
    """
    A citation from a rrxiv paper to another work. May reference another rrxiv paper (target_paper_id), an external work via DOI/arXiv/URL, or a raw BibTeX entry.
    """

    id: str
    """
    Stable, globally unique citation ID within a paper.
    """
    key: str = Field(..., min_length=1)
    """
    BibTeX key as it appears in the paper source.
    """
    target_paper_id: str | None = None
    """
    If the cited work is itself in rrxiv, its paper ID. Null otherwise.
    """
    target_doi: str | None = Field(None, pattern="^10\\.[0-9]{4,9}/[-._;()/:a-zA-Z0-9]+$")
    """
    DOI of the cited work, if any. DOIs are case-insensitive in matching; the registrant's chosen case is preserved.
    """
    target_arxiv_id: str
    """
    arXiv identifier of the cited work, if any (e.g. '2305.12345').
    """
    target_url: AnyUrl | None = None
    """
    Generic URL fallback for the cited work.
    """
    bibtex_entry: str | None = None
    """
    Full BibTeX entry for the cited work. Always present so the citation is verifiable even if external links rot.
    """
    referenced_in: list[str] | None = None
    """
    IDs of sections or claims that cite this work.
    """
    is_self_citation: bool | None = False
    """
    True if the cited work shares an author with the citing paper.
    """


class Citation4(BaseModel):
    """
    A citation from a rrxiv paper to another work. May reference another rrxiv paper (target_paper_id), an external work via DOI/arXiv/URL, or a raw BibTeX entry.
    """

    id: str
    """
    Stable, globally unique citation ID within a paper.
    """
    key: str = Field(..., min_length=1)
    """
    BibTeX key as it appears in the paper source.
    """
    target_paper_id: str | None = None
    """
    If the cited work is itself in rrxiv, its paper ID. Null otherwise.
    """
    target_doi: str | None = Field(None, pattern="^10\\.[0-9]{4,9}/[-._;()/:a-zA-Z0-9]+$")
    """
    DOI of the cited work, if any. DOIs are case-insensitive in matching; the registrant's chosen case is preserved.
    """
    target_arxiv_id: str | None = None
    """
    arXiv identifier of the cited work, if any (e.g. '2305.12345').
    """
    target_url: AnyUrl
    """
    Generic URL fallback for the cited work.
    """
    bibtex_entry: str | None = None
    """
    Full BibTeX entry for the cited work. Always present so the citation is verifiable even if external links rot.
    """
    referenced_in: list[str] | None = None
    """
    IDs of sections or claims that cite this work.
    """
    is_self_citation: bool | None = False
    """
    True if the cited work shares an author with the citing paper.
    """


class Citation5(BaseModel):
    """
    A citation from a rrxiv paper to another work. May reference another rrxiv paper (target_paper_id), an external work via DOI/arXiv/URL, or a raw BibTeX entry.
    """

    id: str
    """
    Stable, globally unique citation ID within a paper.
    """
    key: str = Field(..., min_length=1)
    """
    BibTeX key as it appears in the paper source.
    """
    target_paper_id: str | None = None
    """
    If the cited work is itself in rrxiv, its paper ID. Null otherwise.
    """
    target_doi: str | None = Field(None, pattern="^10\\.[0-9]{4,9}/[-._;()/:a-zA-Z0-9]+$")
    """
    DOI of the cited work, if any. DOIs are case-insensitive in matching; the registrant's chosen case is preserved.
    """
    target_arxiv_id: str | None = None
    """
    arXiv identifier of the cited work, if any (e.g. '2305.12345').
    """
    target_url: AnyUrl | None = None
    """
    Generic URL fallback for the cited work.
    """
    bibtex_entry: str = Field(..., min_length=1)
    """
    Full BibTeX entry for the cited work. Always present so the citation is verifiable even if external links rot.
    """
    referenced_in: list[str] | None = None
    """
    IDs of sections or claims that cite this work.
    """
    is_self_citation: bool | None = False
    """
    True if the cited work shares an author with the citing paper.
    """


class Citation(RootModel[Citation1 | Citation2 | Citation3 | Citation4 | Citation5]):
    root: Citation1 | Citation2 | Citation3 | Citation4 | Citation5 = Field(
        ...,
        examples=[
            {
                "id": "cite-01923f8e:tao2024",
                "key": "tao2024",
                "target_paper_id": None,
                "target_doi": None,
                "target_arxiv_id": "2404.12345",
                "target_url": "https://arxiv.org/abs/2404.12345",
                "bibtex_entry": "@article{tao2024,\n  author = {Tao, Terence},\n  title = {Example title},\n  year = {2024},\n  eprint = {2404.12345},\n  archivePrefix = {arXiv}\n}",
                "referenced_in": ["01923f8e-5b2a-7c4d-9e1f-3a2b1c0d4e5f:queryability"],
                "is_self_citation": False,
            }
        ],
        title="Citation",
    )
    """
    A citation from a rrxiv paper to another work. May reference another rrxiv paper (target_paper_id), an external work via DOI/arXiv/URL, or a raw BibTeX entry.
    """
