# generated by datamodel-codegen:
#   filename:  claim.schema.json
#   timestamp: 2026-05-19T00:00:40+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class ClaimType(StrEnum):
    """
    What kind of claim this is.
    """

    empirical = "empirical"
    theoretical = "theoretical"
    definitional = "definitional"
    methodological = "methodological"
    computational = "computational"


class EvidenceType(StrEnum):
    """
    What kind of evidence supports the claim within the paper.
    """

    proof = "proof"
    experiment = "experiment"
    simulation = "simulation"
    observation = "observation"
    argument = "argument"
    definition = "definition"
    convention = "convention"


class Scope(BaseModel):
    """
    Conditions under which the claim is asserted to hold.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    models: list[str] | None = None
    datasets: list[str] | None = None
    regimes: list[str] | None = None
    assumptions: list[str] | None = None


class Confidence(BaseModel):
    """
    Author's stated confidence in the claim. Optional but encouraged.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    point: float | None = Field(None, ge=0.0, le=1.0)
    lower: float | None = Field(None, ge=0.0, le=1.0)
    upper: float | None = Field(None, ge=0.0, le=1.0)
    rationale: str | None = None


class ReplicationStatus(StrEnum):
    """
    Aggregate replication status. Updated by server based on annotations.
    """

    untested = "untested"
    partial = "partial"
    replicated = "replicated"
    contradicted = "contradicted"
    retracted = "retracted"


class SourceLocation(BaseModel):
    """
    Where in the source the claim originates, for provenance.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    section_id: str | None = None
    paragraph: int | None = Field(None, ge=0)
    raw_source_excerpt: str | None = None


class ExtractedBy(StrEnum):
    """
    Who extracted this claim. Author-extracted claims are canonical from submission; others require confirmation.
    """

    author = "author"
    agent = "agent"
    annotator = "annotator"


class Claim(BaseModel):
    """
    A single falsifiable assertion extracted from a paper. The unit of structured knowledge in the rrxiv corpus. Claim graph edges (depends_on, supports, contradicts, extends) connect claims across papers.
    """

    id: str = Field(..., examples=["01923f8e-5b2a-7c4d-9e1f-3a2b1c0d4e5f:queryability"])
    """
    Stable, globally unique claim ID. Once assigned, NEVER changes. Suggested format: <paper_id>:<local_label>.
    """
    paper_id: str | None = None
    """
    ID of the paper this claim originates in. Same paper may contain many claims.
    """
    statement: str = Field(..., min_length=1)
    """
    The claim itself, expressed as a single falsifiable assertion in natural language. Should be standalone-readable.
    """
    claim_type: ClaimType
    """
    What kind of claim this is.
    """
    evidence_type: EvidenceType
    """
    What kind of evidence supports the claim within the paper.
    """
    scope: Scope | None = None
    """
    Conditions under which the claim is asserted to hold.
    """
    confidence: Confidence | None = None
    """
    Author's stated confidence in the claim. Optional but encouraged.
    """
    depends_on: list[str] | None = None
    """
    IDs of claims (in this or other papers) that this claim relies on. Forms the dependency edges of the claim graph.
    """
    supports: list[str] | None = None
    """
    IDs of claims that this claim is presented as evidence for.
    """
    contradicts: list[str] | None = None
    """
    IDs of claims this claim contradicts. Author asserts the contradiction; community may dispute.
    """
    extends: list[str] | None = None
    """
    IDs of claims this claim extends or generalises.
    """
    replication_status: ReplicationStatus | None = "untested"
    """
    Aggregate replication status. Updated by server based on annotations.
    """
    labels: list[str] | None = None
    """
    Free-form labels (e.g. 'load-bearing', 'speculative', 'background').
    """
    source_location: SourceLocation | None = None
    """
    Where in the source the claim originates, for provenance.
    """
    extracted_by: ExtractedBy | None = None
    """
    Who extracted this claim. Author-extracted claims are canonical from submission; others require confirmation.
    """
    canonical: bool | None = False
    """
    True if confirmed by paper author or via quorum of credentialed annotators.
    """
