# generated by datamodel-codegen:
#   filename:  claim.schema.json
#   timestamp: 2026-05-26T15:45:01+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class ClaimType(StrEnum):
    """
    What kind of claim this is.
    """

    empirical = "empirical"
    theoretical = "theoretical"
    definitional = "definitional"
    methodological = "methodological"
    computational = "computational"


class EvidenceType(StrEnum):
    """
    What kind of evidence supports the claim within the paper.
    """

    proof = "proof"
    experiment = "experiment"
    simulation = "simulation"
    observation = "observation"
    argument = "argument"
    definition = "definition"
    convention = "convention"


class Scope(BaseModel):
    """
    Conditions under which the claim is asserted to hold.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    models: list[str] | None = None
    datasets: list[str] | None = None
    regimes: list[str] | None = None
    assumptions: list[str] | None = None


class Confidence(BaseModel):
    """
    Author's stated confidence in the claim. Optional but encouraged.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    point: float | None = Field(None, ge=0.0, le=1.0)
    lower: float | None = Field(None, ge=0.0, le=1.0)
    upper: float | None = Field(None, ge=0.0, le=1.0)
    rationale: str | None = None


class ReplicationStatus(StrEnum):
    """
    Aggregate replication status. **Server-derived** from annotations per RRP-0019: independent-replication count crosses the per-discipline quorum → `replicated`; contradicting annotations meet or exceed supports → `contradicted`; any non-superseded `claim_retraction` annotation (RRP-0020) → `retracted` (highest precedence). Author-provided values in submitted CIRs are ignored on response; clients should trust the server's derived value.
    """

    untested = "untested"
    partial = "partial"
    replicated = "replicated"
    contradicted = "contradicted"
    retracted = "retracted"


class SourceLocation(BaseModel):
    """
    Where in the source the claim originates, for provenance. Combines the prior section-level provenance fields with file/line span coordinates for the `\\begin{claim}...\\end{claim}` block plus the immediately-following `\\begin{evidence}...\\end{evidence}` block. Lines are 1-indexed. In multi-file papers, `file` is the source-archive-relative path resolved via the flatten-tex marker comments (`% [flatten-tex.py] inlined: <path>` / `% [flatten-tex.py] end: <path>`); single-file papers report the source filename. See RRP-0015.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    section_id: str | None = None
    paragraph: int | None = Field(None, ge=0)
    raw_source_excerpt: str | None = None
    file: str | None = None
    """
    Source-archive-relative path to the file containing the claim, e.g. `books/book01.tex`.
    """
    line_start: int | None = Field(None, ge=1)
    """
    1-indexed line number of the `\\begin{claim}` in `file`.
    """
    line_end: int | None = Field(None, ge=1)
    """
    1-indexed line number of the `\\end{evidence}` (or `\\end{claim}` when no evidence block follows) in `file`.
    """


class Reproducibility(BaseModel):
    """
    Author-attached reproducibility manifest for this claim. Optional; present when the paper's author publishes a reproduction recipe alongside the source. Distinct from replication annotations posted by external readers (those carry their own `reproducibility_manifest_uri`). The web client surfaces a 'Reproduce this' CTA when this field is populated. See RRP-0019 + reproducibility_manifest.schema.json.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    manifest_uri: AnyUrl
    """
    URL of a JSON document conforming to reproducibility_manifest.schema.json. Hosted externally (typically the paper repo's GitHub blob URL at a pinned tag).
    """
    manifest_hash: str | None = Field(None, pattern="^sha256:[a-f0-9]{64}$")
    """
    SHA-256 of the manifest's bytes, allowing clients to detect drift.
    """


class ExtractedBy(StrEnum):
    """
    Who extracted this claim. Author-extracted claims are canonical from submission; others require confirmation.
    """

    author = "author"
    agent = "agent"
    annotator = "annotator"


class ClaimFigure(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str = Field(..., min_length=1)
    """
    Source-archive-relative path to the figure file (e.g. `figures/fig-i-10.tex`). The figure is bundled in the paper's `source.tar.gz` and resolved relative to its root.
    """
    caption: str | None = None
    """
    Plain-text figure caption. Optional; the parser populates it when the figure file contains a `\\caption{...}` macro.
    """


class Claim(BaseModel):
    """
    A single falsifiable assertion extracted from a paper. The unit of structured knowledge in the rrxiv corpus. Claim graph edges (depends_on, supports, contradicts, extends) connect claims across papers.
    """

    id: str = Field(..., examples=["01923f8e-5b2a-7c4d-9e1f-3a2b1c0d4e5f:queryability"])
    """
    Stable, globally unique claim ID. Once assigned, NEVER changes. Suggested format: <paper_id>:<local_label>.
    """
    paper_id: str | None = None
    """
    ID of the paper this claim originates in. Same paper may contain many claims.
    """
    statement: str = Field(..., min_length=1)
    """
    The claim itself, expressed as a single falsifiable assertion in natural language. Should be standalone-readable.
    """
    claim_type: ClaimType
    """
    What kind of claim this is.
    """
    evidence_type: EvidenceType
    """
    What kind of evidence supports the claim within the paper.
    """
    scope: Scope | None = None
    """
    Conditions under which the claim is asserted to hold.
    """
    confidence: Confidence | None = None
    """
    Author's stated confidence in the claim. Optional but encouraged.
    """
    depends_on: list[str] | None = None
    """
    IDs of claims (in this or other papers) that this claim relies on. Forms the dependency edges of the claim graph.
    """
    supports: list[str] | None = None
    """
    IDs of claims that this claim is presented as evidence for.
    """
    contradicts: list[str] | None = None
    """
    IDs of claims this claim contradicts. Author asserts the contradiction; community may dispute.
    """
    extends: list[str] | None = None
    """
    IDs of claims this claim extends or generalises.
    """
    replication_status: ReplicationStatus | None = "untested"
    """
    Aggregate replication status. **Server-derived** from annotations per RRP-0019: independent-replication count crosses the per-discipline quorum → `replicated`; contradicting annotations meet or exceed supports → `contradicted`; any non-superseded `claim_retraction` annotation (RRP-0020) → `retracted` (highest precedence). Author-provided values in submitted CIRs are ignored on response; clients should trust the server's derived value.
    """
    labels: list[str] | None = None
    """
    Free-form labels (e.g. 'load-bearing', 'speculative', 'background').
    """
    proof: str | None = None
    """
    Plain-text proof or evidence body that accompanies this claim. Extracted from the paired `evidence` environment in the source (parser pairs `\\label{prop:X.Y}` to `\\label{ev:X.Y}`). Multi-paragraph; preserves `$...$` math markers verbatim so renderers can hand off to KaTeX or MathJax. `\\dependson` lines are stripped (the edge information already lives in `depends_on`). Optional; CIRs without a paired evidence block omit this field. See RRP-0015.
    """
    figures: list[ClaimFigure] | None = None
    """
    Figures referenced inside the proof body via `\\input{figures/...}`. Each entry records the source-relative path to the figure file and optionally its caption. Paths are relative to the paper's source-archive root (the tarball at `source.uri`). Optional; populated by the parser when the evidence block contains figure inputs. See RRP-0015.
    """
    source_location: SourceLocation | None = None
    """
    Where in the source the claim originates, for provenance. Combines the prior section-level provenance fields with file/line span coordinates for the `\\begin{claim}...\\end{claim}` block plus the immediately-following `\\begin{evidence}...\\end{evidence}` block. Lines are 1-indexed. In multi-file papers, `file` is the source-archive-relative path resolved via the flatten-tex marker comments (`% [flatten-tex.py] inlined: <path>` / `% [flatten-tex.py] end: <path>`); single-file papers report the source filename. See RRP-0015.
    """
    pdf_anchor: str | None = None
    """
    URL fragment that pins the rendered PDF to the page (or named destination) where the claim appears. Typically `#page=N` for raw page anchors, or `#nameddest=<id>` when the PDF carries named destinations. Optional; the parser leaves this null because computing the page number requires the rendered PDF cross-reference table (operators or downstream pipelines populate it). Specified here so future generators have a stable place to put it. See RRP-0015.
    """
    reproducibility: Reproducibility | None = None
    """
    Author-attached reproducibility manifest for this claim. Optional; present when the paper's author publishes a reproduction recipe alongside the source. Distinct from replication annotations posted by external readers (those carry their own `reproducibility_manifest_uri`). The web client surfaces a 'Reproduce this' CTA when this field is populated. See RRP-0019 + reproducibility_manifest.schema.json.
    """
    extracted_by: ExtractedBy | None = None
    """
    Who extracted this claim. Author-extracted claims are canonical from submission; others require confirmation.
    """
    canonical: bool | None = False
    """
    True if confirmed by paper author or via quorum of credentialed annotators.
    """
    views_count: int | None = Field(None, ge=0)
    """
    Server-stamped read counter (RRP-0022 / Sprint 22). Bumped on every GET /api/v0/claims/{id}. Only present on read responses — submitters MUST NOT populate this. Drives the `top_claims_by_views` leaderboard in /stats/pulse.
    """
