# generated by datamodel-codegen:
#   filename:  figure.schema.json
#   timestamp: 2026-05-22T16:48:02+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Figure(BaseModel):
    """
    A figure from a rrxiv paper. Figures don't participate in the claim graph in v0.1; they're targetable by annotations (e.g. dataset_link).
    """

    id: str
    """
    Stable figure ID within the paper.
    """
    label: str = Field(..., min_length=1)
    """
    LaTeX label, e.g. 'fig:rho'. Matches \\label{} inside the figure environment.
    """
    caption: str | None = None
    """
    Plain-text caption.
    """
    uri: str | None = None
    """
    URI to the figure file (PDF, PNG, SVG). May be absolute or relative — relative URIs resolve against `paper.source.uri` (RRP-0015).
    """
    referenced_in: list[str] | None = None
    """
    IDs of sections or claims that reference this figure via \\ref{}.
    """
