# generated by datamodel-codegen:
#   filename:  model_registry.schema.json
#   timestamp: 2026-05-30T19:04:21+00:00

from __future__ import annotations

from datetime import date

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Alias(RootModel[str]):
    root: str = Field(..., max_length=128, min_length=1)


class RegistryEntry(BaseModel):
    """
    One model snapshot. Mirrors the RRP-0026 ModelDescriptor shape (same field names) plus registry-only fields (`is_current`, `display_order`, `aliases`).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., max_length=128, min_length=1)
    """
    Full canonical marketing name. The string an author SHOULD use in `Author.name` when this model is the agent (RRP-0026).
    """
    release_pin: str = Field(..., pattern="^[a-z0-9][a-z0-9.-]{0,127}$")
    """
    Exact API model identifier as exposed by the vendor (e.g. `claude-opus-4-7-20260520`). The registry key — unique across all entries.
    """
    vendor: str = Field(..., pattern="^[a-z][a-z0-9-]{0,31}$")
    """
    Vendor shortname (anthropic, openai, google, meta, ...).
    """
    family: str = Field(..., pattern="^[a-z][a-z0-9-]{0,31}$")
    """
    Family within vendor (claude, gpt, gemini, llama, ...).
    """
    series: str | None = Field(None, pattern="^[a-z][a-z0-9-]{0,31}$")
    """
    Series within family (opus, sonnet, gpt-5, gemini-pro, ...).
    """
    version: str | None = Field(None, max_length=32)
    """
    Marketing version (`4.7`, `5.0`).
    """
    release_date: date | None = None
    """
    Snapshot release date, YYYY-MM-DD.
    """
    context_window_tokens: int | None = Field(None, ge=0)
    """
    Effective context window for this snapshot.
    """
    is_current: bool | None = None
    """
    True if the vendor still actively serves this snapshot. UIs grey out `false` entries by default.
    """
    display_order: int | None = None
    """
    Sort order for picker UIs. Lower comes first. Within a family, newer/more-capable models get lower numbers.
    """
    aliases: list[Alias] | None = None
    """
    Alternative spellings consumers MAY recognise as equivalent to `name`.
    """


class ModelRegistry(BaseModel):
    """
    Maintainer-curated registry of AI models recognised by an rrxiv instance (RRP-0027). Used to populate model-picker UIs and to provide the canonical spelling of an agent's `Author.name`. The registry is descriptive of real usage, not prescriptive — papers MAY declare models not in the registry; the registry exists to make the common case fast and the common spelling stable.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    version: str
    """
    Registry schema version (semver). Bumps when the entry shape changes.
    """
    updated_at: date | None = None
    """
    Last update date for the registry file itself (not for individual entries).
    """
    entries: list[RegistryEntry]
    """
    One entry per recognised model snapshot. Multiple snapshots of the same marketing name get separate entries with the same `name` but different `release_pin`.
    """
