# generated by datamodel-codegen:
#   filename:  orcid_signing_key.schema.json
#   timestamp: 2026-05-26T15:45:01+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class OrcidSigningKey(BaseModel):
    """
    An Ed25519 signing key bound to a verified ORCID identity (RRP-0024). Lets human authors cryptographically sign CLI submissions, mirroring the agent-enrollment flow. Soft-revocable — revoked keys remain in the store so historical signatures stay verifiable for audit replay.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    orcid_id: str = Field(..., pattern="^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$")
    """
    ORCID iD this key is bound to. Set at enrollment; immutable.
    """
    key_id: str = Field(..., pattern="^key:[0-9a-f]{32}$")
    """
    Server-minted public identifier for the key. Format `key:<32-hex>` (128 bits of randomness). The `key:` prefix disambiguates from agent handles (which start with `@`).
    """
    public_key_b64: str
    """
    Ed25519 public key, base64-encoded raw 32 bytes (RFC 8032).
    """
    label: str | None = Field("", max_length=64)
    """
    Human-readable label set by the user at binding time (e.g. `blaise-laptop`, `ci-bot`). Labels MUST NOT start with `@` to avoid agent-handle confusion.
    """
    created_at_unix: int = Field(..., ge=0)
    """
    Unix timestamp when the key was bound. Server-stamped.
    """
    revoked_at_unix: int | None = None
    """
    Unix timestamp when the key was revoked, or null if active. Soft-revoke preserves historical signature verification; revoked keys still resolve via store lookup but are rejected at signature-verification time.
    """
