# generated by datamodel-codegen:
#   filename:  paper_list_item.schema.json
#   timestamp: 2026-05-26T15:01:56+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from .paper_schema import Paper


class Status(StrEnum):
    """
    Paper-level rollup. Precedence: 'retracted' (paper-level retraction erratum) > 'contested' (mixed evidence: at least one replicated claim AND at least one contradicted claim) > 'contradicted' (contradictions, no replications) > 'replicated' (at least one replicated claim, no contradictions) > 'partial' (supports below quorum, no contradictions) > 'untested' (claims + discourse but no replication evidence) > 'preprint' (no claims OR no annotations).
    """

    preprint = "preprint"
    untested = "untested"
    partial = "partial"
    replicated = "replicated"
    contradicted = "contradicted"
    contested = "contested"
    retracted = "retracted"


class Stats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    claims: int = Field(..., ge=0)
    """
    Total claims registered on this paper.
    """
    replicated: int = Field(..., ge=0)
    """
    Count of claims with replication_status='replicated'.
    """
    partial: int = Field(..., ge=0)
    """
    Count of claims with replication_status='partial' (has supporting replications but below the discipline quorum).
    """
    contradicted: int = Field(..., ge=0)
    """
    Count of claims with replication_status='contradicted'.
    """
    contested: int = Field(..., ge=0)
    """
    Count of claims with genuinely mixed evidence (both supports and contradicts on the same claim). The per-claim derivation in v0.x doesn't surface this state — claims resolve to contradicted/replicated/partial individually — so this count stays 0 today; reserved for future schema work.
    """
    untested: int = Field(..., ge=0)
    """
    Count of claims with replication_status='untested' or unset.
    """
    status: Status
    """
    Paper-level rollup. Precedence: 'retracted' (paper-level retraction erratum) > 'contested' (mixed evidence: at least one replicated claim AND at least one contradicted claim) > 'contradicted' (contradictions, no replications) > 'replicated' (at least one replicated claim, no contradictions) > 'partial' (supports below quorum, no contradictions) > 'untested' (claims + discourse but no replication evidence) > 'preprint' (no claims OR no annotations).
    """
    computed_at: AwareDatetime
    """
    When this stats snapshot was computed. Servers SHOULD include; clients MUST treat as a hint, not a cache key.
    """


class PaperListItem(Paper):
    """
    A Paper plus server-computed aggregate stats. Wire shape for GET /api/v0/papers and GET /api/v0/papers/{id}?include=stats. The canonical Paper is immutable; stats are derived from claims and annotations and change as the corpus evolves. See RRP-0012.
    """

    stats: Stats
