# generated by datamodel-codegen:
#   filename:  paper.schema.json
#   timestamp: 2026-05-22T16:48:02+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, EmailStr, Field


class Author(BaseModel):
    name: str
    """
    Display name as the author wishes to be cited.
    """
    orcid: str | None = Field(None, pattern="^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$")
    """
    ORCID iD if available. Strongly recommended for verification.
    """
    affiliation: str | None = None
    email: EmailStr | None = None
    is_agent: bool | None = False
    """
    True if this 'author' is an AI agent. Agents must declare themselves.
    """
    agent_handle: str | None = None
    """
    If is_agent, the agent's persistent identifier on rrxiv.
    """


class Format(StrEnum):
    """
    Source format the paper was authored in.
    """

    latex = "latex"
    typst = "typst"
    markdown = "markdown"
    myst = "myst"
    html = "html"


class Source(BaseModel):
    format: Format
    """
    Source format the paper was authored in.
    """
    uri: str
    """
    URI to retrieve the source bundle (tar.gz containing all source files and figures). May be absolute (e.g. `https://example.org/p.tar.gz`) for off-instance sources or relative (e.g. `/api/v0/papers/<id>/source`) for the canonical case where the bundle is served by the rrxiv host that emitted the CIR — keeping CIRs portable across instances.
    """
    rendered_pdf_uri: str | None = None
    """
    URI to the rendered PDF, if available. Same absolute-or-relative convention as `uri`.
    """
    rendered_html_uri: str | None = None
    """
    URI to a server-rendered HTML view of the paper, if available. Same absolute-or-relative convention as `uri`.
    """
    compile_hash: str | None = None
    """
    Hash of the source bundle for integrity verification.
    """


class Paper(BaseModel):
    """
    A rrxiv paper's metadata. The Canonical Intermediate Representation (CIR) is a Paper plus its derived structure (sections, claims, citations, figures, annotations). Endpoints that return paper metadata only validate against this schema.
    """

    rrxiv_version: str = Field(..., examples=["0.1.0"], pattern="^[0-9]+\\.[0-9]+\\.[0-9]+$")
    """
    Version of the rrxiv protocol this paper conforms to. SemVer.
    """
    id: str = Field(..., examples=["01923f8e-5b2a-7c4d-9e1f-3a2b1c0d4e5f"])
    """
    Stable, canonical identifier for this paper. Format TBD; for v0 use UUIDv7. Once assigned, NEVER changes.
    """
    id_slug: str | None = Field(
        None,
        examples=["rrxiv:2402.00128", "rrxiv:2605.00001"],
        pattern="^rrxiv:[0-9]{4}\\.[0-9]{5}$",
    )
    """
    Human-friendly paper identifier of the form rrxiv:YYMM.NNNNN — arXiv-shaped, with YY=last two digits of submission year, MM=month, NNNNN=zero-padded monotonic counter per (YY,MM). Server-minted at submission, unique per server instance. Used in URLs, citations, and human-readable references. The canonical machine identifier remains `id`. Once assigned, NEVER changes. Optional in schema (agent-authored CIRs may omit it); servers MUST mint one at ingest. See RRP-0013.
    """
    version: str = Field(..., examples=["v1", "v2"], pattern="^v[0-9]+$")
    """
    Paper revision. The same paper may have v1, v2, etc. Each version is immutable once submitted.
    """
    previous_version: str | None = None
    """
    ID of the previous version of this paper, if any. Null for v1.
    """
    title: str = Field(..., max_length=500, min_length=1)
    authors: list[Author] = Field(..., min_length=1)
    abstract: str
    """
    Plain-text abstract. Math should be expressed in LaTeX inline.
    """
    submitted_at: AwareDatetime
    """
    ISO 8601 timestamp when this version was submitted to rrxiv. Set by server, immutable.
    """
    license: str = Field(..., examples=["CC-BY-4.0", "CC-BY-SA-4.0", "CC0-1.0"])
    """
    SPDX license identifier for the paper content. rrxiv recommends CC-BY-4.0.
    """
    topics: list[str] | None = None
    """
    Topic IDs from the rrxiv controlled vocabulary. May be added or refined post-submission via annotations.
    """
    source: Source
