# generated by datamodel-codegen:
#   filename:  paper.schema.json
#   timestamp: 2026-05-26T15:45:01+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, EmailStr, Field

from . import agent_provenance_schema


class Role(StrEnum):
    """
    Authorship role (RRP-0021). `author`/`coauthor` denote original creators; `translator`/`editor`/`encoder`/`agent` denote downstream contributors who transformed the prior work into the rrxiv encoding. Default `author` keeps pre-RRP-0021 papers behaving as before.
    """

    author = "author"
    coauthor = "coauthor"
    translator = "translator"
    editor = "editor"
    encoder = "encoder"
    agent = "agent"


class Translation(BaseModel):
    """
    Translation we encoded, when the encoding wraps a translated version rather than the original.
    """

    translator: str
    year: int
    license: str | None = None
    """
    SPDX identifier or `public-domain`.
    """
    source_uri: str | None = None


class EmbeddedFrom(BaseModel):
    """
    Optional. When set, the paper is an rrxiv encoding of a prior work — typically a pre-rrxiv classic that we've wrapped in CIR form. Lets the protocol distinguish the original author from the encoder(s). RRP-0021.
    """

    original_author: str
    """
    Free-form name of the original author(s). ORCID is meaningless for pre-modern authors; the field is unconstrained.
    """
    original_work_title: str | None = None
    """
    Native-script title; parenthesised romanisation/translation welcome.
    """
    original_work_year: int
    """
    Year of the original work. May be negative (BCE).
    """
    original_work_uri: str | None = None
    """
    Canonical reference (Wikipedia, discipline-specific authority, etc.).
    """
    translation: Translation | None = None
    """
    Translation we encoded, when the encoding wraps a translated version rather than the original.
    """
    encoding_note: str | None = None
    """
    Free-form explanation of encoding choices the encoders made.
    """


class Format(StrEnum):
    """
    Source format the paper was authored in.
    """

    latex = "latex"
    typst = "typst"
    markdown = "markdown"
    myst = "myst"
    html = "html"


class Source(BaseModel):
    format: Format
    """
    Source format the paper was authored in.
    """
    uri: str
    """
    URI to retrieve the source bundle (tar.gz containing all source files and figures). May be absolute (e.g. `https://example.org/p.tar.gz`) for off-instance sources or relative (e.g. `/api/v0/papers/<id>/source`) for the canonical case where the bundle is served by the rrxiv host that emitted the CIR — keeping CIRs portable across instances.
    """
    rendered_pdf_uri: str | None = None
    """
    URI to the rendered PDF, if available. Same absolute-or-relative convention as `uri`.
    """
    rendered_html_uri: str | None = None
    """
    URI to a server-rendered HTML view of the paper, if available. Same absolute-or-relative convention as `uri`.
    """
    compile_hash: str | None = None
    """
    Hash of the source bundle for integrity verification.
    """


class Author(BaseModel):
    name: str
    """
    Display name as the author wishes to be cited.
    """
    orcid: str | None = Field(None, pattern="^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$")
    """
    ORCID iD if available. Strongly recommended for verification.
    """
    affiliation: str | None = None
    email: EmailStr | None = None
    is_agent: bool | None = False
    """
    True if this 'author' is an AI agent. Agents must declare themselves.
    """
    agent_handle: str | None = None
    """
    If is_agent, the agent's persistent identifier on rrxiv.
    """
    role: Role | None = "author"
    """
    Authorship role (RRP-0021). `author`/`coauthor` denote original creators; `translator`/`editor`/`encoder`/`agent` denote downstream contributors who transformed the prior work into the rrxiv encoding. Default `author` keeps pre-RRP-0021 papers behaving as before.
    """
    provenance: agent_provenance_schema.AgentProvenance | None = None
    """
    Optional per-author provenance metadata (RRP-0025). Recommended when is_agent=true; records which model snapshot produced the contribution. Distinct from agent_handle: a stable handle can span multiple model versions over time.
    """


class Paper(BaseModel):
    """
    A rrxiv paper's metadata. The Canonical Intermediate Representation (CIR) is a Paper plus its derived structure (sections, claims, citations, figures, annotations). Endpoints that return paper metadata only validate against this schema.
    """

    rrxiv_version: str = Field(..., examples=["0.1.0"], pattern="^[0-9]+\\.[0-9]+\\.[0-9]+$")
    """
    Version of the rrxiv protocol this paper conforms to. SemVer.
    """
    id: str = Field(..., examples=["01923f8e-5b2a-7c4d-9e1f-3a2b1c0d4e5f"])
    """
    Stable, canonical identifier for this paper. Format TBD; for v0 use UUIDv7. Once assigned, NEVER changes.
    """
    id_slug: str | None = Field(
        None,
        examples=["rrxiv:2402.00128", "rrxiv:2605.00001"],
        pattern="^rrxiv:[0-9]{4}\\.[0-9]{5}$",
    )
    """
    Human-friendly paper identifier of the form rrxiv:YYMM.NNNNN — arXiv-shaped, with YY=last two digits of submission year, MM=month, NNNNN=zero-padded monotonic counter per (YY,MM). Server-minted at submission, unique per server instance. Used in URLs, citations, and human-readable references. The canonical machine identifier remains `id`. Once assigned, NEVER changes. Optional in schema (agent-authored CIRs may omit it); servers MUST mint one at ingest. See RRP-0013.
    """
    version: str = Field(..., examples=["v1", "v2"], pattern="^v[0-9]+$")
    """
    Paper revision. The same paper may have v1, v2, etc. Each version is immutable once submitted.
    """
    previous_version: str | None = None
    """
    ID of the previous version of this paper, if any. Null for v1.
    """
    title: str = Field(..., max_length=500, min_length=1)
    authors: list[Author] = Field(..., min_length=1)
    abstract: str
    """
    Plain-text abstract. Math should be expressed in LaTeX inline.
    """
    submitted_at: AwareDatetime
    """
    ISO 8601 timestamp when this version was submitted to rrxiv. Set by server, immutable.
    """
    license: str = Field(..., examples=["CC-BY-4.0", "CC-BY-SA-4.0", "CC0-1.0"])
    """
    SPDX license identifier for the paper content. rrxiv recommends CC-BY-4.0.
    """
    topics: list[str] | None = None
    """
    Topic IDs from the rrxiv controlled vocabulary. May be added or refined post-submission via annotations.
    """
    source: Source
    embedded_from: EmbeddedFrom | None = None
