# generated by datamodel-codegen:
#   filename:  paper_list_item.schema.json
#   timestamp: 2026-05-19T00:00:40+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from .paper_schema import Paper


class Status(StrEnum):
    """
    Paper-level rollup. 'preprint' = no annotations yet. 'untested' = annotations exist but no replications/contradictions. 'replicated' = replications without contradictions or partials. 'contested' = any mix of replications + non-replication evidence, or contradictions without replications. 'retracted' = paper has a retraction erratum.
    """

    preprint = "preprint"
    untested = "untested"
    replicated = "replicated"
    contested = "contested"
    retracted = "retracted"


class Stats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    claims: int = Field(..., ge=0)
    """
    Total claims registered on this paper.
    """
    replicated: int = Field(..., ge=0)
    """
    Count of claims with replication_status='replicated'.
    """
    contradicted: int = Field(..., ge=0)
    """
    Count of claims with replication_status='contradicted'.
    """
    contested: int = Field(..., ge=0)
    """
    Count of claims with replication_status='partial' (mixed evidence).
    """
    untested: int = Field(..., ge=0)
    """
    Count of claims with replication_status='untested' or unset.
    """
    status: Status
    """
    Paper-level rollup. 'preprint' = no annotations yet. 'untested' = annotations exist but no replications/contradictions. 'replicated' = replications without contradictions or partials. 'contested' = any mix of replications + non-replication evidence, or contradictions without replications. 'retracted' = paper has a retraction erratum.
    """
    computed_at: AwareDatetime
    """
    When this stats snapshot was computed. Servers SHOULD include; clients MUST treat as a hint, not a cache key.
    """


class PaperListItem(Paper):
    """
    A Paper plus server-computed aggregate stats. Wire shape for GET /api/v0/papers and GET /api/v0/papers/{id}?include=stats. The canonical Paper is immutable; stats are derived from claims and annotations and change as the corpus evolves. See RRP-0012.
    """

    stats: Stats
