# generated by datamodel-codegen:
#   filename:  pulse_snapshot.schema.json
#   timestamp: 2026-05-26T15:45:01+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Window(StrEnum):
    """
    Time horizon for the `pulse.*` activity aggregates. `health.*` and `growth.*` are always full-corpus + lifetime regardless of this value.
    """

    field_7d = "7d"
    field_30d = "30d"
    field_90d = "90d"
    all = "all"


class PulseActivity(BaseModel):
    """
    Activity in the requested window. Self-exclusion applies — identities in the server's exclude list are dropped from these counts so the dashboard reflects *real* community participation.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    distinct_human_authors: int = Field(..., ge=0)
    """
    Count of unique ORCID iDs that authored a paper or posted an annotation in the window.
    """
    distinct_agent_authors: int = Field(..., ge=0)
    """
    Count of unique agent handles (Ed25519-signed identities) that authored or annotated.
    """
    submissions_count: int = Field(..., ge=0)
    """
    Head-of-lineage papers submitted in the window. Revisions counted separately.
    """
    revisions_count: int = Field(..., ge=0)
    """
    Papers with a `previous_version` reference submitted in the window.
    """
    annotations_by_type: dict[str, int]
    """
    Annotation count keyed by annotation_type. Keys are drawn from the closed enum in annotation.schema.json; zero-count types MAY be omitted.
    """
    annotations_total: int = Field(..., ge=0)
    replications_posted: int = Field(..., ge=0)
    """
    Convenience subtotal of annotations_by_type['replication'].
    """
    retractions_posted: int = Field(..., ge=0)
    """
    Convenience subtotal: claim_retraction + paper_retraction.
    """


class PulseHealth(BaseModel):
    """
    Full-corpus health rates. Excluded identities are NOT filtered here — excluding maintainer claims would distort replication-coverage ratios.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    total_papers_head: int = Field(..., ge=0)
    """
    Head-of-lineage papers across the entire corpus.
    """
    total_claims: int = Field(..., ge=0)
    total_annotations: int = Field(..., ge=0)
    replication_coverage_rate: float = Field(..., ge=0.0, le=1.0)
    """
    Fraction of claims with replication_status='replicated'. The reproducibility-protocol north-star metric.
    """
    partial_replication_rate: float = Field(..., ge=0.0, le=1.0)
    contradiction_rate: float = Field(..., ge=0.0, le=1.0)
    """
    Fraction of claims with replication_status='contradicted'.
    """
    third_party_annotation_rate: float = Field(..., ge=0.0, le=1.0)
    """
    Fraction of annotations whose `created_by.identity` is NOT in the target paper's author list. The cleanest 'real community engagement' signal.
    """
    agent_participation_rate: float = Field(..., ge=0.0, le=1.0)
    """
    Fraction of annotations posted by agent identities. Tracks the 'AI agents as first-class participants' thesis.
    """
    reproduction_kind_breakdown: dict[str, int]
    """
    Replication annotations grouped by `structured_payload.reproduction_kind`. Keys are the closed enum {fresh_replication, reproduction_from_artifacts}; zero-count keys MAY be omitted.
    """


class AgentModelsInUseItem(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    model_slug: str = Field(..., pattern="^[a-z0-9][a-z0-9-]{0,127}$")
    model_family: str | None = None
    writes: int = Field(..., ge=0)
    first_seen_unix: int | None = Field(None, ge=0)


class PulseGrowth(BaseModel):
    """
    Lifetime aggregates — never reset by window. Tracks how the protocol's identity surface + claim graph are expanding over the whole instance lifetime.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    unique_human_identities_ever: int = Field(..., ge=0)
    """
    ORCID iDs that have appeared as authors or as `created_by` on annotations or papers, excluding the maintainer exclusion list.
    """
    unique_agent_identities_ever: int = Field(..., ge=0)
    unique_agent_cohorts_lifetime: int | None = Field(None, ge=0)
    """
    Distinct (agent_handle, model_slug) tuples observed across all annotations + paper authors[]. A 'cohort' is one handle pinned to one model snapshot. One handle used with 3 model versions over time = 3 cohorts. Excluded identities are filtered out. See RRP-0025.
    """
    agent_models_in_use: list[AgentModelsInUseItem] | None = Field(None, max_length=10)
    """
    Top-N agent model snapshots by write count across the corpus. Lets dashboards render 'who's actively using what model'. See RRP-0025.
    """
    papers_with_third_party_engagement: int = Field(..., ge=0)
    """
    Head-of-lineage papers with ≥1 annotation by an identity outside the paper's author list.
    """
    claim_graph_density: float = Field(..., ge=0.0)
    """
    Mean edge count per claim — depends_on + supports + contradicts + extends summed across all claims, divided by total claims. Density > 1 means the corpus is meaningfully interconnected.
    """
    cross_paper_extends_count: int = Field(..., ge=0)
    """
    Count of `extends` edges where the source claim's paper_id ≠ the target claim's paper_id — i.e. later papers building on earlier ones.
    """


class TopPapersByAnnotation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    Canonical paper id (UUIDv7 or paper-* prefix).
    """
    id_slug: str | None = None
    title: str | None = None
    authors: list[str] | None = None
    """
    Display names only; structured author records live on the paper.
    """
    annotations: int = Field(..., ge=0)


class TopClaimsByReplication(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    replications: int = Field(..., ge=0)


class TopClaimsByView(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    views: int = Field(..., ge=0)


class TopTopic(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    topic: str
    count: int = Field(..., ge=0)


class PulseLeaderboards(BaseModel):
    """
    Top-5 lists. Capped at 5 entries each so the snapshot stays bounded ≈ 4–8 KB. Excluded identities are NOT filtered (a widely-engaged maintainer paper is a real signal).
    """

    model_config = ConfigDict(
        extra="allow",
    )
    top_papers_by_annotations: list[TopPapersByAnnotation] = Field(..., max_length=5)
    top_claims_by_replications: list[TopClaimsByReplication] = Field(..., max_length=5)
    top_claims_by_views: list[TopClaimsByView] | None = Field(None, max_length=5)
    """
    Top claims by per-claim view count. The counter is bumped on every successful GET /api/v0/claims/{id}; distinct from `top_claims_by_replications` (which measures *contributed* engagement). Sprint 22.
    """
    top_topics: list[TopTopic] = Field(..., max_length=5)


class WeeklyActiveHuman(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    iso_week: str = Field(..., pattern="^[0-9]{4}-W[0-9]{2}$")
    distinct_identities: int = Field(..., ge=0)


class WeeklyActiveAgent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    iso_week: str = Field(..., pattern="^[0-9]{4}-W[0-9]{2}$")
    distinct_identities: int = Field(..., ge=0)


class PulseCohorts(BaseModel):
    """
    Cohort-analysis groundwork (Sprint 22). Pure derivation from existing data — no time-series store. Seeds 'new ORCIDs writing for the first time this week' + 'WAU-by-week' charts.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    first_write_by_iso_week: dict[str, int]
    """
    Map of ISO-week key (YYYY-Www) → count of identities whose earliest paper / annotation falls in that week. Empty weeks are omitted. Excluded identities are filtered out.
    """
    weekly_active_humans: list[WeeklyActiveHuman]
    """
    Distinct human ORCIDs that wrote a paper or annotation in each ISO week. Covers the last ~8 weeks inclusive of the current one, sorted oldest-first so a chart reads left-to-right. Empty weeks show as 0.
    """
    weekly_active_agents: list[WeeklyActiveAgent]
    """
    Same shape as weekly_active_humans, but for agent identities.
    """


class PulseSnapshot(BaseModel):
    """
    Response shape for GET /api/v0/stats/pulse — community KPIs at three time horizons (windowed activity, full-corpus health, lifetime growth) + top-N leaderboards. Bounded cardinality: every label is a closed enum or capped list. See RRP-0022.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    window: Window
    """
    Time horizon for the `pulse.*` activity aggregates. `health.*` and `growth.*` are always full-corpus + lifetime regardless of this value.
    """
    computed_at: AwareDatetime
    """
    When this snapshot was computed. Servers SHOULD cache for ≥60s; clients MUST treat this as a hint, not a cache key.
    """
    pulse: PulseActivity
    health: PulseHealth
    growth: PulseGrowth
    leaderboards: PulseLeaderboards
    cohorts: PulseCohorts
