# generated by datamodel-codegen:
#   filename:  reproducibility_manifest.schema.json
#   timestamp: 2026-05-26T15:01:56+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class Environment(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    kind: str
    """
    Container or environment kind. v0.x recommends `docker`; the field is an open string so future manifests can add `conda`, `nix`, `modal`, etc.
    """
    image: str | None = None
    """
    Container image reference (e.g. `ghcr.io/example/repro:abc123`). Required when kind=docker.
    """
    digest: str | None = Field(None, pattern="^sha256:[a-f0-9]{64}$")
    """
    Content-addressable digest of the image. Strongly recommended.
    """
    platform: str | None = None
    """
    Target platform (e.g. `linux/amd64`).
    """


class Kind(StrEnum):
    url = "url"
    git = "git"
    huggingface = "huggingface"
    s3 = "s3"
    ipfs = "ipfs"
    inline = "inline"


class Data(BaseModel):
    """
    Input data needed to run the reproduction. Optional — many reproductions have no external data.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind | None = None
    uri: AnyUrl | None = None
    hash: str | None = Field(None, pattern="^sha256:[a-f0-9]{64}$")
    ref: str | None = None
    """
    Git ref / HF revision / S3 version-ID when applicable.
    """


class ExpectedOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str
    """
    Output path relative to the workspace inside the container.
    """
    hash: str | None = Field(None, pattern="^sha256:[a-f0-9]{64}$")
    """
    Expected SHA-256 of the file's bytes for byte-deterministic reproductions.
    """
    description: str | None = None


class ReproducibilityManifest(BaseModel):
    """
    A small JSON file co-located with a paper's or replicator's code, describing the runtime environment and how to reproduce a claim. Linked from `replication` annotations via `reproducibility_manifest_uri` and from author-attached claim fields via `claim.reproducibility.manifest_uri`. See RRP-0019 for design rationale.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    version: Literal["1.0"]
    """
    Manifest schema version. Pinned to 1.0 for v0.x.
    """
    title: str | None = None
    """
    Human-readable title for the manifest (e.g. 'Reproduction of Claim I.47').
    """
    claim_uri: AnyUrl
    """
    Canonical URI of the claim this manifest reproduces. Typically https://rrxiv.com/claims/<claim_id>.
    """
    environment: Environment
    data: Data | None = None
    """
    Input data needed to run the reproduction. Optional — many reproductions have no external data.
    """
    entrypoint: str = Field(..., min_length=1)
    """
    Command to invoke inside the environment (e.g. `python run.py --seed 0`). Convention: deterministic; running it twice should produce identical `expected_outputs`.
    """
    expected_outputs: list[ExpectedOutput] | None = None
    """
    Files (and optionally their hashes) the entrypoint is expected to produce. Empty for reproductions that only assert non-byte-level outcomes (e.g. plotted figures judged visually).
    """
    estimated_runtime_minutes: float | None = Field(None, ge=0.0)
    """
    Rough runtime estimate so a reproducer can decide whether to run.
    """
    estimated_cost_usd: float | None = Field(None, ge=0.0)
    """
    Rough cost estimate in USD (cloud-compute back-of-napkin).
    """
    notes: str | None = None
    """
    Free-form prose for nuances the structured fields can't capture.
    """
