# generated by datamodel-codegen:
#   filename:  revision_diff.schema.json
#   timestamp: 2026-05-25T19:27:55+00:00

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class VersionRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    paper_id: UUID
    version: str = Field(..., pattern="^v[0-9]+$")
    id_slug: str | None = None


class AddedClaim(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    claim_id: str
    local_id: str
    """
    Stable label from the source (e.g. `prop:I.10`).
    """
    statement: str
    claim_type: str


class RemovedClaim(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    claim_id: str
    local_id: str
    statement: str


class FieldsChangedEnum(Enum):
    statement = "statement"
    proof = "proof"
    claim_type = "claim_type"
    evidence_type = "evidence_type"
    figures = "figures"
    depends_on = "depends_on"
    supports = "supports"
    contradicts = "contradicts"
    extends = "extends"
    source_location = "source_location"


class Kind(Enum):
    """
    Direction of the hunk.
    """

    equal = "equal"
    added = "added"
    removed = "removed"


class DiffHunk(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind
    """
    Direction of the hunk.
    """
    text: str


class AbstractDiff(BaseModel):
    """
    Word-level diff hunks for the abstract. Present iff abstract_changed=true.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    hunks: list[DiffHunk]


class TextDiff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    hunks: list[DiffHunk]


class ModifiedClaim(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_claim_id: str
    """
    Claim ID in the `from` version.
    """
    to_claim_id: str
    """
    Claim ID in the `to` version.
    """
    local_id: str
    """
    Stable label shared across both versions.
    """
    fields_changed: list[FieldsChangedEnum]
    """
    List of claim fields that differ between the two versions.
    """
    statement_diff: TextDiff | None = None
    """
    Word-level diff of the statement. Present iff `statement` is in `fields_changed`.
    """
    proof_diff: TextDiff | None = None
    """
    Word-level diff of the proof. Present iff `proof` is in `fields_changed`.
    """


class Claims(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    added: list[AddedClaim]
    """
    Claims present in `to` with no counterpart in `from`.
    """
    removed: list[RemovedClaim]
    """
    Claims present in `from` with no counterpart in `to`.
    """
    modified: list[ModifiedClaim]
    """
    Claim pairs (one in `from`, one in `to`) matched by the deterministic matching rule (RRP-0017 §Claim matching rule) whose contents differ.
    """
    unchanged_count: int = Field(..., ge=0)
    """
    Number of claim pairs that matched and are byte-identical.
    """


class RevisionDiff(BaseModel):
    """
    Structural diff between two versions of a paper. `from` is the older paper; `to` is the newer. Both must share the same lineage (one's `previous_version` chain must reach the other). Returned by GET /api/v0/papers/{id}/diff?from=<prior_paper_id>. See RRP-0017 for design rationale.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    from_: VersionRef = Field(..., alias="from")
    """
    Older version's identification.
    """
    to: VersionRef
    """
    Newer version's identification.
    """
    abstract_changed: bool
    """
    True if the abstract differs after `tex_to_text` normalisation.
    """
    abstract_diff: AbstractDiff | None = None
    """
    Word-level diff hunks for the abstract. Present iff abstract_changed=true.
    """
    topics_changed: bool
    """
    True if the paper's topic set changed.
    """
    topics_added: list[str] | None = None
    """
    Topics present in `to` but not in `from`.
    """
    topics_removed: list[str] | None = None
    """
    Topics present in `from` but not in `to`.
    """
    claims: Claims
    computed_at: AwareDatetime
    """
    Server's ISO-8601 timestamp for when the diff was computed. Cached responses preserve the original computation time.
    """
