# generated by datamodel-codegen:
#   filename:  section.schema.json
#   timestamp: 2026-05-19T00:00:40+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field


class Type(StrEnum):
    """
    Section level. Maps from LaTeX \\section / \\subsection / \\subsubsection / \\paragraph and the abstract environment.
    """

    abstract = "abstract"
    section = "section"
    subsection = "subsection"
    subsubsection = "subsubsection"
    paragraph = "paragraph"
    appendix = "appendix"


class Section(BaseModel):
    """
    A section heading from a rrxiv paper. The section hierarchy is the document structure used by clients that browse/navigate papers and by claim queries that filter by section.
    """

    id: str
    """
    Stable section ID within the paper. Usually the LaTeX label (e.g. 'sec:intro').
    """
    type: Type
    """
    Section level. Maps from LaTeX \\section / \\subsection / \\subsubsection / \\paragraph and the abstract environment.
    """
    title: str = Field(..., min_length=1)
    order: int = Field(..., ge=0)
    """
    Canonical display order within the paper. Sections of the same level use this as the tiebreaker.
    """
    parent_id: str | None = None
    """
    ID of the parent section if this is nested. Null for top-level sections.
    """
    raw_source: str | None = None
    """
    Raw source text of this section, captured if the parser was instructed to preserve it.
    """
    rendered_html: str | None = None
    """
    Rendered HTML form of this section, if a renderer produced one.
    """
    claims_in_section: list[str] | None = None
    """
    Reverse index from section to claims that appear in it.
    """
