# generated by datamodel-codegen:
#   filename:  submission_request.schema.json
#   timestamp: 2026-05-22T15:51:00+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class SubmissionRequest(BaseModel):
    """
    Wire format for POST /api/v0/submissions. Multipart-encoded: the `cir` and `bundle` fields are multipart file parts; the remaining fields are form fields. See spec/0005-submission.md for prose; RRP-0016 for the rationale.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    cir: str
    """
    JSON-encoded CIR validating against cir.schema.json. Uploaded as a multipart file part named `cir`. Servers parse the body as JSON and validate.
    """
    bundle: str
    """
    Source bundle as a `.tar.gz` file part named `bundle`. Constraints in spec/0005-submission.md §Source bundle format: no symlinks, no executables, ≤100 MB uncompressed, UTF-8, single top-level directory.
    """
    previous_version: UUID | None = None
    """
    Paper ID of the prior version when submitting a revision. Server sets `previous_version` on the stored paper to this value; null/absent means this is v1. Server validates that the referenced paper exists and belongs to the same author lineage (or that the submitting identity is on the prior version's author list).
    """
    revision_summary: str | None = Field(None, max_length=8192)
    """
    Optional plaintext summary of changes for a revision submission. When present, the server may auto-generate a `revision_summary` annotation (see RRP-0017) authored by the submitter and attached to the new paper. Authors may add structured `highlights` via a follow-up annotation.
    """
    dry_run: bool | None = False
    """
    When true, the server performs all validation + compile + parse + diff steps but does NOT persist the submission. Returns the would-be paper_id (null), would-be id_slug, computed CIR, and any revision_diff. Useful for CI. The Idempotency-Key, if present, is NOT stored — a subsequent real submission with the same key still gets a fresh ID.
    """
    client_compile_hash: str | None = Field(None, pattern="^[a-f0-9]{64}$")
    """
    SHA-256 of the bundle bytes as computed by the submitting client (lowercase hex). Server recomputes and rejects on mismatch (400 with code `bundle_hash_mismatch`). Advisory in v0.x; may become required in v1.0.
    """
