"""``rrxiv conformance <server-url>`` — drives the canonical
e2e story against any URL.

The same shape as ``tests/test_conformance_e2e.py`` but exposed as a
CLI subcommand so other-language client+server pairs can be tested
against the rrxiv-python tooling.

Exits 0 on full pass; non-zero on the first failed assertion with
a clear diagnostic.
"""

from __future__ import annotations

import base64
import json
import time
from typing import Annotated

import httpx
import typer


def conformance(
    server: Annotated[
        str,
        typer.Argument(
            help="API base URL, e.g. http://127.0.0.1:8000/api/v0"
        ),
    ],
    keep_state: Annotated[
        bool,
        typer.Option(
            "--keep-state/--clean",
            help=(
                "Don't delete created records on success. Useful when "
                "you want to inspect server state afterwards."
            ),
        ),
    ] = False,
) -> None:
    """Run the canonical conformance suite against a server."""
    api_base = server.rstrip("/")
    typer.secho(f"Running conformance suite against {api_base}", fg=typer.colors.CYAN)

    try:
        from rrxiv.auth import (
            AgentEnrollmentRequest,
            enroll_agent,
        )
        from rrxiv.auth.agent import (
            build_enrollment_payload,
            sign_enrollment_payload,
        )
        from rrxiv.client import (
            AgentSigningKey,
            RrxivClient,
        )
        from rrxiv.client.signatures import AgentSigningAuth
    except ImportError as e:
        typer.secho(
            f"conformance suite needs the [agent] extra: {e}",
            fg=typer.colors.RED,
            err=True,
        )
        raise typer.Exit(2) from e

    handle = f"@conformance-{int(time.time())}"
    typer.echo(f"[1/9] enrolling agent {handle}…")
    signing = AgentSigningKey.generate(handle=handle)
    pub_b64 = base64.standard_b64encode(signing.public_key_bytes()).decode("ascii")
    payload = build_enrollment_payload(
        handle=handle, public_key_b64=pub_b64, issued_at=int(time.time())
    )
    sig_b64 = sign_enrollment_payload(
        payload=payload, private_key_bytes=signing.private_key_bytes()
    )
    bearer = enroll_agent(
        api_base=api_base,
        request=AgentEnrollmentRequest(
            handle=handle,
            public_key_b64=pub_b64,
            payload_b64=base64.standard_b64encode(payload).decode("ascii"),
            signature_b64=sig_b64,
        ),
    )
    typer.secho("      OK (token issued)", fg=typer.colors.GREEN)

    paper_id = f"paper-conformance-{int(time.time())}"
    cir = {
        "rrxiv_version": "0.1.0",
        "id": paper_id,
        "version": "v1",
        "title": "rrxiv conformance fixture",
        "authors": [{"name": "Conformance Suite"}],
        "abstract": "Generated by `rrxiv conformance`.",
        "submitted_at": "2026-05-06T00:00:00Z",
        "license": "CC-BY-4.0",
        "source": {"format": "latex", "uri": f"{api_base}/papers/{paper_id}/source"},
        "topics": ["conformance"],
    }

    typer.echo(f"[2/9] submitting paper {paper_id}…")
    with httpx.Client(headers={"Authorization": f"Bearer {bearer.token}"}) as c:
        resp = c.post(
            f"{api_base}/submissions",
            files={
                "cir": (
                    "c.json",
                    json.dumps(cir).encode("utf-8"),
                    "application/json",
                ),
                "bundle": (
                    "p.tar.gz",
                    b"conformance fixture source",
                    "application/gzip",
                ),
            },
            auth=AgentSigningAuth(signing),
        )
    _expect(resp, 201, "POST /submissions")
    typer.secho("      OK (paper minted)", fg=typer.colors.GREEN)

    typer.echo("[3/9] paper visible in /papers…")
    with RrxivClient(api_base, auth=bearer, agent_signing_key=signing) as client:
        page = client.list_papers()
        assert any(p["id"] == paper_id for p in page["items"]), "paper missing"
    typer.secho("      OK", fg=typer.colors.GREEN)

    typer.echo("[4/9] /search/papers finds it…")
    with httpx.Client() as c:
        resp = c.get(f"{api_base}/search/papers", params={"q": "conformance"})
    _expect(resp, 200, "GET /search/papers")
    ids = [p["id"] for p in resp.json()["items"]]
    assert paper_id in ids, f"search did not return {paper_id}: ids={ids}"
    typer.secho("      OK", fg=typer.colors.GREEN)

    ann_id = f"ann-conformance-{int(time.time())}"
    typer.echo(f"[5/9] creating annotation {ann_id} (signed)…")
    with RrxivClient(api_base, auth=bearer, agent_signing_key=signing) as client:
        ann = client.create_annotation(
            {
                "id": ann_id,
                "target_id": paper_id,
                "target_type": "paper",
                "annotation_type": "comment",
                "content": "Conformance suite annotation.",
                "created_at": "2026-05-06T00:00:00Z",
                "created_by": {
                    "identity_type": "agent",
                    "identity": handle,
                },
            }
        )
        assert ann.id == ann_id
    typer.secho("      OK", fg=typer.colors.GREEN)

    typer.echo("[6/9] reading annotation back…")
    with RrxivClient(api_base, auth=bearer, agent_signing_key=signing) as client:
        ann2 = client.get_annotation(ann_id)
        assert ann2.id == ann_id
    typer.secho("      OK", fg=typer.colors.GREEN)

    typer.echo("[7/9] creating snapshot…")
    with httpx.Client(
        headers={"Authorization": f"Bearer {bearer.token}"}
    ) as c:
        resp = c.post(f"{api_base}/snapshots", auth=AgentSigningAuth(signing))
    _expect(resp, 201, "POST /snapshots")
    manifest = resp.json()
    typer.secho("      OK", fg=typer.colors.GREEN)

    typer.echo("[8/9] /snapshots/latest reflects this snapshot…")
    with httpx.Client() as c:
        resp = c.get(f"{api_base}/snapshots/latest")
    _expect(resp, 200, "GET /snapshots/latest")
    assert resp.json()["snapshot_id"] == manifest["snapshot_id"]
    typer.secho("      OK", fg=typer.colors.GREEN)

    typer.echo("[9/9] downloading + verifying snapshot blob…")
    with httpx.Client() as c:
        resp = c.get(_resolve_blob_uri(api_base, manifest["blob_uri"]))
    _expect(resp, 200, "GET snapshot blob")
    assert resp.content[:2] == b"\x1f\x8b", "snapshot is not gzipped"
    import io
    import tarfile

    with tarfile.open(fileobj=io.BytesIO(resp.content), mode="r:gz") as tar:
        names = tar.getnames()
        assert f"papers/{paper_id}.json" in names
        assert f"annotations/{ann_id}.json" in names
    typer.secho("      OK", fg=typer.colors.GREEN)

    typer.secho("\nConformance suite passed.", fg=typer.colors.GREEN, bold=True)


def _expect(resp: httpx.Response, want: int, what: str) -> None:
    if resp.status_code != want:
        typer.secho(
            f"\n      FAIL ({what} returned {resp.status_code}, want {want})\n"
            f"      body: {resp.text[:300]}",
            fg=typer.colors.RED,
            err=True,
        )
        raise typer.Exit(1)


def _resolve_blob_uri(api_base: str, blob_uri: str) -> str:
    """Snapshot manifests carry server-relative URIs (e.g. /api/v0/...).
    Resolve to absolute against the configured base."""
    if blob_uri.startswith(("http://", "https://")):
        return blob_uri
    base_root = api_base.split("/api/v0")[0]
    if blob_uri.startswith("/api/v0"):
        return base_root + blob_uri
    if blob_uri.startswith("/"):
        return api_base.rstrip("/") + blob_uri
    return api_base.rstrip("/") + "/" + blob_uri


__all__ = ["conformance"]
